-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Media_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "media"

  - Id - column name
  - Thumbnail - column name
  - Uploaded\_at - column name
  - User\_id - column name

-}
type Media_select_column
    = Id
    | Thumbnail
    | Uploaded_at
    | User_id


list : List Media_select_column
list =
    [ Id, Thumbnail, Uploaded_at, User_id ]


decoder : Decoder Media_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "id" ->
                        Decode.succeed Id

                    "thumbnail" ->
                        Decode.succeed Thumbnail

                    "uploaded_at" ->
                        Decode.succeed Uploaded_at

                    "user_id" ->
                        Decode.succeed User_id

                    _ ->
                        Decode.fail ("Invalid Media_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Media_select_column -> String
toString enum____ =
    case enum____ of
        Id ->
            "id"

        Thumbnail ->
            "thumbnail"

        Uploaded_at ->
            "uploaded_at"

        User_id ->
            "user_id"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Media_select_column
fromString enumString____ =
    case enumString____ of
        "id" ->
            Just Id

        "thumbnail" ->
            Just Thumbnail

        "uploaded_at" ->
            Just Uploaded_at

        "user_id" ->
            Just User_id

        _ ->
            Nothing
