-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Message_select_column_message_aggregate_bool_exp_bool_and_arguments_columns exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select "message\_aggregate\_bool\_exp\_bool\_and\_arguments\_columns" columns of table "message"

  - Tweeted - column name

-}
type Message_select_column_message_aggregate_bool_exp_bool_and_arguments_columns
    = Tweeted


list : List Message_select_column_message_aggregate_bool_exp_bool_and_arguments_columns
list =
    [ Tweeted ]


decoder : Decoder Message_select_column_message_aggregate_bool_exp_bool_and_arguments_columns
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "tweeted" ->
                        Decode.succeed Tweeted

                    _ ->
                        Decode.fail ("Invalid Message_select_column_message_aggregate_bool_exp_bool_and_arguments_columns type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Message_select_column_message_aggregate_bool_exp_bool_and_arguments_columns -> String
toString enum____ =
    case enum____ of
        Tweeted ->
            "tweeted"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Message_select_column_message_aggregate_bool_exp_bool_and_arguments_columns
fromString enumString____ =
    case enumString____ of
        "tweeted" ->
            Just Tweeted

        _ ->
            Nothing
