-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Session_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "session"

  - Session\_pkey - unique or primary key constraint on columns "id"

-}
type Session_constraint
    = Session_pkey


list : List Session_constraint
list =
    [ Session_pkey ]


decoder : Decoder Session_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "session_pkey" ->
                        Decode.succeed Session_pkey

                    _ ->
                        Decode.fail ("Invalid Session_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Session_constraint -> String
toString enum____ =
    case enum____ of
        Session_pkey ->
            "session_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Session_constraint
fromString enumString____ =
    case enumString____ of
        "session_pkey" ->
            Just Session_pkey

        _ ->
            Nothing
