-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Task_fixed_time_update_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "task\_fixed\_time"

  - Created\_at - column name
  - Enabled - column name
  - Fri - column name
  - Id - column name
  - Mon - column name
  - Random - column name
  - Sat - column name
  - Sun - column name
  - Tag\_id - column name
  - Thu - column name
  - Tue - column name
  - Tweet\_at - column name
  - Updated\_at - column name
  - User\_id - column name
  - Wed - column name

-}
type Task_fixed_time_update_column
    = Created_at
    | Enabled
    | Fri
    | Id
    | Mon
    | Random
    | Sat
    | Sun
    | Tag_id
    | Thu
    | Tue
    | Tweet_at
    | Updated_at
    | User_id
    | Wed


list : List Task_fixed_time_update_column
list =
    [ Created_at, Enabled, Fri, Id, Mon, Random, Sat, Sun, Tag_id, Thu, Tue, Tweet_at, Updated_at, User_id, Wed ]


decoder : Decoder Task_fixed_time_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "created_at" ->
                        Decode.succeed Created_at

                    "enabled" ->
                        Decode.succeed Enabled

                    "fri" ->
                        Decode.succeed Fri

                    "id" ->
                        Decode.succeed Id

                    "mon" ->
                        Decode.succeed Mon

                    "random" ->
                        Decode.succeed Random

                    "sat" ->
                        Decode.succeed Sat

                    "sun" ->
                        Decode.succeed Sun

                    "tag_id" ->
                        Decode.succeed Tag_id

                    "thu" ->
                        Decode.succeed Thu

                    "tue" ->
                        Decode.succeed Tue

                    "tweet_at" ->
                        Decode.succeed Tweet_at

                    "updated_at" ->
                        Decode.succeed Updated_at

                    "user_id" ->
                        Decode.succeed User_id

                    "wed" ->
                        Decode.succeed Wed

                    _ ->
                        Decode.fail ("Invalid Task_fixed_time_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Task_fixed_time_update_column -> String
toString enum____ =
    case enum____ of
        Created_at ->
            "created_at"

        Enabled ->
            "enabled"

        Fri ->
            "fri"

        Id ->
            "id"

        Mon ->
            "mon"

        Random ->
            "random"

        Sat ->
            "sat"

        Sun ->
            "sun"

        Tag_id ->
            "tag_id"

        Thu ->
            "thu"

        Tue ->
            "tue"

        Tweet_at ->
            "tweet_at"

        Updated_at ->
            "updated_at"

        User_id ->
            "user_id"

        Wed ->
            "wed"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Task_fixed_time_update_column
fromString enumString____ =
    case enumString____ of
        "created_at" ->
            Just Created_at

        "enabled" ->
            Just Enabled

        "fri" ->
            Just Fri

        "id" ->
            Just Id

        "mon" ->
            Just Mon

        "random" ->
            Just Random

        "sat" ->
            Just Sat

        "sun" ->
            Just Sun

        "tag_id" ->
            Just Tag_id

        "thu" ->
            Just Thu

        "tue" ->
            Just Tue

        "tweet_at" ->
            Just Tweet_at

        "updated_at" ->
            Just Updated_at

        "user_id" ->
            Just User_id

        "wed" ->
            Just Wed

        _ ->
            Nothing
