-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Task_rss_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "task\_rss"

  - Task\_rss\_pkey - unique or primary key constraint on columns "id"

-}
type Task_rss_constraint
    = Task_rss_pkey


list : List Task_rss_constraint
list =
    [ Task_rss_pkey ]


decoder : Decoder Task_rss_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "task_rss_pkey" ->
                        Decode.succeed Task_rss_pkey

                    _ ->
                        Decode.fail ("Invalid Task_rss_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Task_rss_constraint -> String
toString enum____ =
    case enum____ of
        Task_rss_pkey ->
            "task_rss_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Task_rss_constraint
fromString enumString____ =
    case enumString____ of
        "task_rss_pkey" ->
            Just Task_rss_pkey

        _ ->
            Nothing
