-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ScalarCodecs exposing (..)

import Graphql.Codec exposing (Codec)
import Hasura.Scalar exposing (defaultCodecs)
import Iso8601
import Json.Decode as JD exposing (Decoder)
import Json.Encode as JE
import LocalTime exposing (LocalTime)
import Prng.Uuid as Uuid
import Time


type alias Jsonb =
    JD.Value


type alias Timestamptz =
    Time.Posix


type alias Time =
    LocalTime


type alias Uuid =
    Uuid.Uuid


codecs : Hasura.Scalar.Codecs Time Timestamptz Uuid
codecs =
    Hasura.Scalar.defineCodecs
        { codecTime = codecTime
        , codecTimestamptz = codecTimestamptz
        , codecUuid = codecUuid
        }


codecJsonb : Codec JD.Value
codecJsonb =
    { encoder = identity
    , decoder = JD.value
    }


codecTimestamptz : Codec Time.Posix
codecTimestamptz =
    { encoder = Iso8601.encode
    , decoder = Iso8601.decoder
    }


codecTime : Codec LocalTime
codecTime =
    { encoder = LocalTime.toString >> JE.string
    , decoder = LocalTime.decoder
    }


codecUuid : Codec Uuid.Uuid
codecUuid =
    { encoder = Uuid.encode
    , decoder = Uuid.decoder
    }
