-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Message exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.Union
import Json.Decode as Decode
import ScalarCodecs


created_at : SelectionSet ScalarCodecs.Timestamptz Hasura.Object.Message
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


id : SelectionSet ScalarCodecs.Uuid Hasura.Object.Message
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
media :
    SelectionSet decodesTo Hasura.Object.Media
    -> SelectionSet (Maybe decodesTo) Hasura.Object.Message
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)


media_id : SelectionSet (Maybe ScalarCodecs.Uuid) Hasura.Object.Message
media_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "media_id" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


priority : SelectionSet Int Hasura.Object.Message
priority =
    Object.selectionForField "Int" "priority" [] Decode.int


{-| An object relationship
-}
tag :
    SelectionSet decodesTo Hasura.Object.Tag
    -> SelectionSet (Maybe decodesTo) Hasura.Object.Message
tag object____ =
    Object.selectionForCompositeField "tag" [] object____ (Basics.identity >> Decode.nullable)


tag_id : SelectionSet (Maybe ScalarCodecs.Uuid) Hasura.Object.Message
tag_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "tag_id" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


text : SelectionSet String Hasura.Object.Message
text =
    Object.selectionForField "String" "text" [] Decode.string


tweeted : SelectionSet Bool Hasura.Object.Message
tweeted =
    Object.selectionForField "Bool" "tweeted" [] Decode.bool


updated_at : SelectionSet ScalarCodecs.Timestamptz Hasura.Object.Message
updated_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updated_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


{-| An object relationship
-}
user :
    SelectionSet decodesTo Hasura.Object.User
    -> SelectionSet decodesTo Hasura.Object.Message
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity


user_id : SelectionSet String Hasura.Object.Message
user_id =
    Object.selectionForField "String" "user_id" [] Decode.string
