-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.SaveMediaOutput exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.Union
import Json.Decode as Decode
import ScalarCodecs


id : SelectionSet ScalarCodecs.Uuid Hasura.Object.SaveMediaOutput
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


thumbnail : SelectionSet String Hasura.Object.SaveMediaOutput
thumbnail =
    Object.selectionForField "String" "thumbnail" [] Decode.string


uploadedAt : SelectionSet ScalarCodecs.Timestamptz Hasura.Object.SaveMediaOutput
uploadedAt =
    Object.selectionForField "ScalarCodecs.Timestamptz" "uploadedAt" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


userId : SelectionSet String Hasura.Object.SaveMediaOutput
userId =
    Object.selectionForField "String" "userId" [] Decode.string
