-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Session exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.Union
import Json.Decode as Decode
import ScalarCodecs


access_token : SelectionSet String Hasura.Object.Session
access_token =
    Object.selectionForField "String" "access_token" [] Decode.string


expires_in : SelectionSet (Maybe Int) Hasura.Object.Session
expires_in =
    Object.selectionForField "(Maybe Int)" "expires_in" [] (Decode.int |> Decode.nullable)


id : SelectionSet String Hasura.Object.Session
id =
    Object.selectionForField "String" "id" [] Decode.string


issued_at : SelectionSet ScalarCodecs.Timestamptz Hasura.Object.Session
issued_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "issued_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


name : SelectionSet (Maybe String) Hasura.Object.Session
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


refresh_token : SelectionSet (Maybe String) Hasura.Object.Session
refresh_token =
    Object.selectionForField "(Maybe String)" "refresh_token" [] (Decode.string |> Decode.nullable)


user_name : SelectionSet (Maybe String) Hasura.Object.Session
user_name =
    Object.selectionForField "(Maybe String)" "user_name" [] (Decode.string |> Decode.nullable)
