-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Task_rss exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.Union
import Json.Decode as Decode
import ScalarCodecs


created_at : SelectionSet ScalarCodecs.Timestamptz Hasura.Object.Task_rss
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


enabled : SelectionSet Bool Hasura.Object.Task_rss
enabled =
    Object.selectionForField "Bool" "enabled" [] Decode.bool


fri : SelectionSet Bool Hasura.Object.Task_rss
fri =
    Object.selectionForField "Bool" "fri" [] Decode.bool


id : SelectionSet ScalarCodecs.Uuid Hasura.Object.Task_rss
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


last_pub_date : SelectionSet (Maybe ScalarCodecs.Timestamptz) Hasura.Object.Task_rss
last_pub_date =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "last_pub_date" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


mon : SelectionSet Bool Hasura.Object.Task_rss
mon =
    Object.selectionForField "Bool" "mon" [] Decode.bool


random : SelectionSet Bool Hasura.Object.Task_rss
random =
    Object.selectionForField "Bool" "random" [] Decode.bool


sat : SelectionSet Bool Hasura.Object.Task_rss
sat =
    Object.selectionForField "Bool" "sat" [] Decode.bool


sun : SelectionSet Bool Hasura.Object.Task_rss
sun =
    Object.selectionForField "Bool" "sun" [] Decode.bool


template : SelectionSet (Maybe String) Hasura.Object.Task_rss
template =
    Object.selectionForField "(Maybe String)" "template" [] (Decode.string |> Decode.nullable)


thu : SelectionSet Bool Hasura.Object.Task_rss
thu =
    Object.selectionForField "Bool" "thu" [] Decode.bool


tue : SelectionSet Bool Hasura.Object.Task_rss
tue =
    Object.selectionForField "Bool" "tue" [] Decode.bool


tweet_at : SelectionSet ScalarCodecs.Time Hasura.Object.Task_rss
tweet_at =
    Object.selectionForField "ScalarCodecs.Time" "tweet_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTime |> .decoder)


updated_at : SelectionSet ScalarCodecs.Timestamptz Hasura.Object.Task_rss
updated_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updated_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


url : SelectionSet String Hasura.Object.Task_rss
url =
    Object.selectionForField "String" "url" [] Decode.string


{-| An object relationship
-}
user :
    SelectionSet decodesTo Hasura.Object.User
    -> SelectionSet decodesTo Hasura.Object.Task_rss
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity


user_id : SelectionSet String Hasura.Object.Task_rss
user_id =
    Object.selectionForField "String" "user_id" [] Decode.string


wed : SelectionSet Bool Hasura.Object.Task_rss
wed =
    Object.selectionForField "Bool" "wed" [] Decode.bool
