-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.User_min_fields exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.Union
import Json.Decode as Decode
import ScalarCodecs


email : SelectionSet (Maybe String) Hasura.Object.User_min_fields
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


email_confirm_code : SelectionSet (Maybe String) Hasura.Object.User_min_fields
email_confirm_code =
    Object.selectionForField "(Maybe String)" "email_confirm_code" [] (Decode.string |> Decode.nullable)


email_confirm_code_issued_at : SelectionSet (Maybe ScalarCodecs.Timestamptz) Hasura.Object.User_min_fields
email_confirm_code_issued_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "email_confirm_code_issued_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


email_confirmed_at : SelectionSet (Maybe ScalarCodecs.Timestamptz) Hasura.Object.User_min_fields
email_confirmed_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "email_confirmed_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe String) Hasura.Object.User_min_fields
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


last_seen : SelectionSet (Maybe ScalarCodecs.Timestamptz) Hasura.Object.User_min_fields
last_seen =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "last_seen" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


registered_at : SelectionSet (Maybe ScalarCodecs.Timestamptz) Hasura.Object.User_min_fields
registered_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "registered_at" [] (ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)
