tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/_wildcard.still-bott.com.pem
        keyFile: /etc/traefik/certs/_wildcard.still-bott.com-key.pem
  certificates:
    - certFile: /etc/traefik/certs/_wildcard.still-bott.com.pem
      keyFile: /etc/traefik/certs/_wildcard.still-bott.com-key.pem
    - certFile: /etc/traefik/certs/still-bott.com.pem
      keyFile: /etc/traefik/certs/still-bott.com-key.pem
# http:
#   routers:
#     minio-admin:
#       entryPoints:
#         - web
#     rule: "Host(`minio.still-bott.com`)"
#     service: "minio-admin"
#     tls: {}

# services:
#   minio-admin:
#     loadBalancer:
#       servers:
#         - url: "http://host.docker.internal:9001/"
#     - api:
#       loadBalancer:
#         servers:
#           - url: "http://api.docker.internal:3000/"
