-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object exposing (..)


type BooleanOutput
    = BooleanOutput


type ConfirmEmailOutput
    = ConfirmEmailOutput


type DeleteImageOutput
    = DeleteImageOutput


type GetTokenOutput
    = GetTokenOutput


type GetUserOutput
    = GetUserOutput


type Media
    = Media


type Media_aggregate
    = Media_aggregate


type Media_aggregate_fields
    = Media_aggregate_fields


type Media_max_fields
    = Media_max_fields


type Media_min_fields
    = Media_min_fields


type Media_mutation_response
    = Media_mutation_response


type Message
    = Message


type Message_aggregate
    = Message_aggregate


type Message_aggregate_fields
    = Message_aggregate_fields


type Message_avg_fields
    = Message_avg_fields


type Message_max_fields
    = Message_max_fields


type Message_min_fields
    = Message_min_fields


type Message_mutation_response
    = Message_mutation_response


type Message_stddev_fields
    = Message_stddev_fields


type Message_stddev_pop_fields
    = Message_stddev_pop_fields


type Message_stddev_samp_fields
    = Message_stddev_samp_fields


type Message_sum_fields
    = Message_sum_fields


type Message_var_pop_fields
    = Message_var_pop_fields


type Message_var_samp_fields
    = Message_var_samp_fields


type Message_variance_fields
    = Message_variance_fields


type MinioGetUploadUrlOutput
    = MinioGetUploadUrlOutput


type RegisterEmailOutput
    = RegisterEmailOutput


type Role
    = Role


type Role_aggregate
    = Role_aggregate


type Role_aggregate_fields
    = Role_aggregate_fields


type Role_max_fields
    = Role_max_fields


type Role_min_fields
    = Role_min_fields


type Role_mutation_response
    = Role_mutation_response


type SaveMediaOutput
    = SaveMediaOutput


type Session
    = Session


type Session_aggregate
    = Session_aggregate


type Session_aggregate_fields
    = Session_aggregate_fields


type Session_avg_fields
    = Session_avg_fields


type Session_max_fields
    = Session_max_fields


type Session_min_fields
    = Session_min_fields


type Session_mutation_response
    = Session_mutation_response


type Session_stddev_fields
    = Session_stddev_fields


type Session_stddev_pop_fields
    = Session_stddev_pop_fields


type Session_stddev_samp_fields
    = Session_stddev_samp_fields


type Session_sum_fields
    = Session_sum_fields


type Session_var_pop_fields
    = Session_var_pop_fields


type Session_var_samp_fields
    = Session_var_samp_fields


type Session_variance_fields
    = Session_variance_fields


type Tag
    = Tag


type Tag_aggregate
    = Tag_aggregate


type Tag_aggregate_fields
    = Tag_aggregate_fields


type Tag_max_fields
    = Tag_max_fields


type Tag_min_fields
    = Tag_min_fields


type Tag_mutation_response
    = Tag_mutation_response


type Task_fixed_time
    = Task_fixed_time


type Task_fixed_time_aggregate
    = Task_fixed_time_aggregate


type Task_fixed_time_aggregate_fields
    = Task_fixed_time_aggregate_fields


type Task_fixed_time_max_fields
    = Task_fixed_time_max_fields


type Task_fixed_time_min_fields
    = Task_fixed_time_min_fields


type Task_fixed_time_mutation_response
    = Task_fixed_time_mutation_response


type Task_rss
    = Task_rss


type Task_rss_aggregate
    = Task_rss_aggregate


type Task_rss_aggregate_fields
    = Task_rss_aggregate_fields


type Task_rss_max_fields
    = Task_rss_max_fields


type Task_rss_min_fields
    = Task_rss_min_fields


type Task_rss_mutation_response
    = Task_rss_mutation_response


type User
    = User


type User_aggregate
    = User_aggregate


type User_aggregate_fields
    = User_aggregate_fields


type User_max_fields
    = User_max_fields


type User_min_fields
    = User_min_fields


type User_mutation_response
    = User_mutation_response
