-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.ScalarCodecs exposing (..)

import Hasura.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Time =
    Hasura.Scalar.Time


type alias Timestamptz =
    Hasura.Scalar.Timestamptz


type alias Uuid =
    Hasura.Scalar.Uuid


codecs : Hasura.Scalar.Codecs Time Timestamptz Uuid
codecs =
    Hasura.Scalar.defineCodecs
        { codecTime = defaultCodecs.codecTime
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        , codecUuid = defaultCodecs.codecUuid
        }
